### ISSUE TITLE
Add Template Systemd Service

### ISSUE THREAD

**Issue by lorenzogood** [SouthwestRoboticsProgramming/TagTracker#9]
Add a template Systemd service that teams can use.

**Comment by drakeerv** [comment]
I made a systemd file in our [fork](https://github.com/4533-phoenix/TagTracker). It also automatically installs the systemd service and starts it.

**Comment by lorenzogood** [comment]
You can pull request over from the fork

**Comment by lorenzogood** [comment]
We unfortunately cannot accept this contribution due to bad committer guidelines. Please Provide a Clean Commit only adding the service, and pull request.

**Comment by drakeerv** [comment]
Here is a clean [fork](https://github.com/drakeerv/TagTracker)

**Comment by lorenzogood** [comment]
@drakeerv Thanks!, pull request it and I will approve.
